### ISSUE TITLE
About cmmd_cleaned_label.csv

### ISSUE THREAD

**Issue by jessicachen01** [dangnh0611/kaggle_rsna_breast_cancer#2]
Hi
I am also working on a project using CMMD dataset, the original dataset just provides the label of one side which causing confusion especially for D2 data.

The file structure is like:
D2-0032
  - 07-18-2010-NA-NA-49155
    - 1.000000-NA-92065
     - 1-1.dcm
     - 1-2.dcm
     - 1-3.dcm
     - 1-4.dcm

Could you let me know how can you get the cmmd_cleaned_label.csv? and how do you distinguish the left and right image from the above four file?

Thanks in advance!

**Comment by dangnh0611** [comment]
Hi,
The laterality (left-right) can be extracted from dicom metadata associated with each dicom file (*.dcm).
For D2 subset, the missing side (laterality) usually means that side is normal (non-cancer).
For details to get the cmmd_cleaned_label.csv, refer to the function `stage1_process_cmmd()` defined [here](https://github.com/dangnh0611/kaggle_rsna_breast_cancer/blob/4cb4684e0a0f3404804498f5ddc1cbb098b43a32/src/tools/_prepair_classification_dataset_stage1.py#LL261C11-L261C11)

**Comment by jessicachen01** [comment]
Thank you! it helps a lot.
