### ISSUE TITLE
Building  docker image 

### ISSUE THREAD

**Issue by ramon349** [dangnh0611/kaggle_rsna_breast_cancer#4]
Hello, 

Thank you for sharing your repository and details on running your code. I've been having issues building the docker image where the final  Torch2trt fails due to missing the CUDA_HOME variable.  I've tried the install process without Torch2trt  but found that Cuda is unavailable. Do you have any suggestions on how to remedy this issue? 

Best,

**Comment by dangnh0611** [comment]
Hi, was CUDA available on your system, e.g `nvcc -V`
You can skip Torch2Trt installation if you want, and also no TensorRT at all. But you need to modify some code to make it work with Torch model instead of TensorRT, especially the YOLOX related-parts.
