### ISSUE TITLE
Install requirements - python version

### ISSUE THREAD

**Issue by Kaschi14** [dangnh0611/kaggle_rsna_breast_cancer#5]
Which python version did you use, was it Python3.8?
And installing with pip install -r requirements.txt is not possible because some of the installations are with local files. Which versions does this packages have?

**Comment by dangnh0611** [comment]
Hi, the provided requirements.txt is just for reference purpose only. Another words, if you have trouble installing some packages, take requirements.txt as just a reference for version clarification.
The recommended way to install all neccesary dependencies is using docker.
You can also install the default package names (without specific version `==`) binded with your OS distribution/Python listed in requirements.txt and it should work.
