### ISSUE TITLE
Change dockerfile image

### ISSUE THREAD

**Issue by Kaschi14** [dangnh0611/kaggle_rsna_breast_cancer#6]
Hi
ultralytics/yolov5 docker image just got an update two days ago and is now running with Python 3.10
This results in an error "AttributeError: module 'collections' has no attribute 'Sequence'". Fix it by changing the first row in the dockerfile as follows:

```
#FROM ultralytics/yolov5:latest
FROM ultralytics/yolov5:v7.0
```

**Comment by dangnh0611** [comment]
Many thanks, updated !
