### ISSUE TITLE
CMMD dataset

### ISSUE THREAD

**Issue by MoeinSorkhei** [dangnh0611/kaggle_rsna_breast_cancer#7]
Hello,
The meta-data in CMMD dataset does not clearly describe the image paths corresponding to the patient/exam.
For instance, patient with D1-0087 has Benign left breast but Malignant right breast (according to CMMD_clinicaldata_revision file), but the image directory does not specify which image is left/right breast, which makes it problematic for evaluation.

Do you have any thoughts?

**Comment by dangnh0611** [comment]
have you tried https://github.com/dangnh0611/kaggle_rsna_breast_cancer/issues/2 ?
